name: Deployment pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
#  test:
#    needs: simple_deployment_pipeline
#    uses: ./.github/workflows/playwright-test.yml

      - name: Set up secret file
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo ${{secrets.RENDER_SERVICE_ID}}
          echo ${{secrets.RENDER_API_KEY}}
  deploy:
#    needs: test
    uses: ./.github/workflows/render-deploy.yml