name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  workflow_dispatch:



jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
  test:
    needs: simple_deployment_pipeline
    uses: ./.github/workflows/playwright-test.yml
  deploy:
    if: ${{ github.event_name == 'push' && !contains(github.event.commits.*.message, '#skip') }}
    needs: test
    uses: ./.github/workflows/render-deploy.yml
    secrets:
      RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
  tag_release:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  send_discord_notification:
    if: ${{ always() }}
    needs: [simple_deployment_pipeline, test, deploy, tag_release]
    runs-on: ubuntu-20.04
    steps:
      - name: Test Success
        uses: stegzilla/discord-notify@v2
        if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
        with:
            webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
            title: Test Succeeded!
            colour: '#008000'
            message: "**${{ github.event.pull_request.title }}**\n**Creator:** ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}"
            include_image: true
            avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            username: GitHub PR Notifier
      - name: Test Failure
        uses: stegzilla/discord-notify@v2
        if: ${{ always() && contains(needs.*.result, 'failure') }}
        with:
            webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
            title: Test Failed!
            colour: '#FF0000'
            message: "**${{ github.event.pull_request.title }}**\n**Creator:** ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}"
            include_image: true
            avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            username: GitHub PR Notifier
      - name: Test Cancelled
        uses: stegzilla/discord-notify@v2
        if: ${{ always() && contains(needs.*.result, 'cancelled') }}
        with:
            webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
            title: Test Cancelled!
            colour: '#808080'
            message: "**${{ github.event.pull_request.title }}**\n**Creator:** ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}"
            include_image: true
            avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            username: GitHub PR Notifier