name: Deploy to Render

on:
    workflow_call:
      secrets:
        RENDER_DEPLOY_HOOK_URL:
          required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy
      # Only run this step if the branch is main
      if: github.ref == 'refs/heads/main'
      env:
        RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        curl "$RENDER_DEPLOY_HOOK_URL"
